<h2><?php echo $this->locale->_('SignUp') ?></h2>
<br>
<?php echo $this->tag->form("signup/add"); ?>
    <label for="name"><?php echo $this->locale->_('Name') ?>:
        <input type="text" name="name">
    </label><br><br>
    <label for="password"><?php echo $this->locale->_('Password') ?>:
        <input type="text" name="password">
    </label><br><br>
    <label for="email"><?php echo $this->locale->_('Email') ?>:
        <input type="text" name="email">
    </label><br><br>
    <label for="role"><?php echo $this->locale->_('Type') ?>:
        <select name="role">
            <option value="">-<?php echo $this->locale->_('Select') ?>-</option>
            <option value="user"><?php echo $this->locale->_('User') ?></option>
            <option value="manager"><?php echo $this->locale->_('Manager') ?></option>
            <option value="admin"><?php echo $this->locale->_('Admin')?></option>
        </select>
    </label><br><br>

    <input class="btn btn-primary" type="submit" value="<?php echo $this->locale->_('Add') ?>">
</form>
<br>
<?php
echo $this->tag->linkTo([
    '/',
    $this->locale->_('Back'),
    'class' => 'btn btn-primary'
]);